@startuml{GetFEM.png}
skinparam dpi 300
mesh        "1"   --o "0.." mesh_fem
fem         "1"   --o "0.." mesh_fem
mesh        "1"   --o "0.." mesh_im
integ       "1"   --o "0.." mesh_im
mesh_fem    "1"   --o "0.." brick
mesh_im     "1"   --o "0.." brick
brick       "0.." --o "1"   model
time_scheme "0.." --o "1"   model
@enduml
